services:
  - type: web
    name: codecompiler
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    aptPackages:
      - openjdk-17-jdk
